# Spring Boot 应用配置
spring:
  application:
    name: pf4j-scaffold
  
  # Jackson JSON配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
      indent-output: true

# Web服务器配置
server:
  port: 8081
  servlet:
    context-path: /

# 日志配置
logging:
  level:
    com.example.pf4j: DEBUG
    org.pf4j: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/pf4j-scaffold.log
    max-size: 10MB
    max-history: 30

# 插件相关配置
pf4j:
  plugin-path: plugins
  development-mode: true
  scan-interval: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# 应用信息
info:
  app:
    name: PF4J Dynamic Loading Scaffold
    description: 基于PF4J和Spring Boot的动态插件加载系统
    version: 1.0.0
    author: Developer
  java:
    version: ${java.version}
  spring:
    version: ${spring-boot.version}