# Spring Boot 应用配置
spring:
  application:
    name: pf4j-scaffold
  
  # Jackson JSON配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
  
  # MySQL数据源配置 - 远程数据库
  datasource:
    url: jdbc:mysql://192.168.100.221:3306/java_admin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: java_admin
    password: 2BLTERiG425JNYMt
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  
  # JPA配置
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  # Thymeleaf配置
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

# Web服务器配置
server:
  port: 8081
  servlet:
    context-path: /

# 日志配置
logging:
  level:
    com.example.pf4j: DEBUG
    org.pf4j: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/pf4j-scaffold.log
    max-size: 10MB
    max-history: 30

# 插件相关配置
pf4j:
  plugin-path: plugins
  development-mode: true
  scan-interval: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# 应用信息
info:
  app:
    name: PF4J Dynamic Loading Scaffold
    description: 基于PF4J和Spring Boot的动态插件加载系统
    version: 1.0.0
    author: Developer
  java:
    version: ${java.version}
  spring:
    version: ${spring-boot.version}